language: php

sudo: false

php:
  - '7.1'

services:
  - mysql

env:
  global:
    SYMFONY_VERSION: '3.3.*'
    SYMFONY_FLAGS: '--env=test'

git:
  depth: 1

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - phpenv config-add config.ini
  - phpenv config-rm xdebug.ini

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --prefer-stable

before_script:
  - 'php bin/console doctrine:database:create $SYMFONY_FLAGS'
  - 'php bin/console doctrine:schema:create $SYMFONY_FLAGS'

script: ./vendor/bin/phpunit

branches:
  only:
    - master
