# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\User: bcrypt

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
          id: AppBundle\Provider\UserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
                csrf_token_id: authenticate
                csrf_token_generator: security.csrf.token_manager
                provider: user_provider
            logout:
              path: logout
            anonymous: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
